{% set data = load_setup_py_data() %}

package:
    name: sqlalchemy-singlestoredb
    version: {{ data.get('version') }}

source:
    path: ..

build:
    noarch: python
    number: {{ environ.get('PACKAGE_BUILD_NUMBER', '0') }}
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - python {{ python }}
        - pip
    run:
        - singlestoredb
        - sqlalchemy

test:
    imports:
        - sqlalchemy_singlestoredb
    requires:
        - coverage
        - nose2
        - pandas
        - pytest
    commands:
        - nose2 -v sqlalchemy_singlestoredb.tests.test_basics

about:
    home: https://github.com/singlestore-labs/sqlalchemy-singlestoredb
    license: Apache 2.0
    license_file: ../LICENSE
    summary: SingleStoreDB SQLAlchemy Dialect
    doc_url: https://singlestore.github.io/sqlalchemy-singlestore/index.html
    dev_url: https://github.com/singlestore/sqlalchemy-singlestoredb
