# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish packages

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      publish:
        description: "Publish packages on success?"
        required: true
        type: boolean
        default: false

jobs:
  publish:

    runs-on: ubuntu-latest

    services:
      singlestore:
        image: singlestore/cluster-in-a-box:latest
        ports:
          - 3306:3306
          - 8080:8080
        env:
          LICENSE_KEY: ${{ secrets.SINGLESTORE_LICENSE }}
          ROOT_PASSWORD: "root"
          START_AFTER_INIT: "Y"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      - name: Build PyPI package
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build

      - name: Build Conda package
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
          conda update conda
          conda install conda-build anaconda-client
          cd conda.recipe
          mkdir artifacts
          conda build -c singlestore -c conda-forge --no-anaconda-upload --output-folder artifacts .
        env:
          SINGLESTORE_URL: "root:root@127.0.0.1:3306"

#      - name: Publish PyPI package
#        if: ${{ github.event.inputs.publish }}
#        uses: pypa/gh-action-pypi-publish@717ba43cfbb0387f6ce311b169a825772f54d295
#        with:
#          user: __token__
#          password: "${{ secrets.PYPI_TOKEN }}"

#      - name: Publish Conda package
#        if: ${{ github.event.inputs.publish }}
#        run: |
#          echo $CONDA/bin >> $GITHUB_PATH
#          anaconda -t "${{ secrets.ANACONDA_TOKEN }}" upload --no-progress --user SingleStore --label main artifacts/noarch/sqlalchemy-singlestore-*.tar.bz2
